language: node_js
node_js:
- '10'
dist: trusty
before_script:
- npm install
- sudo chown root /opt/google/chrome/chrome-sandbox
- sudo chmod 4755 /opt/google/chrome/chrome-sandbox
script:
- npm test
cache:
  directories:
  - node_modules
env:
- CXX=g++-4.8 CC=gcc-4.8